export const trabajadoresDB = [
  {
    id_trabajador: 1,
    nombre: "Luis Ernesto",
    apellidos: "Rodriguez",
    ci: "920151569",
    telefono: "58155198",
    puesto: "Mantenimiento",
    direccion: "Calle 6 #11 Reparto Versalles",
    salario: 31000,
    foto_perfil: "jorgerepartidor.jpg",
    id_usuario: 1,
  },
  {
    id_trabajador: 2,
    nombre: "Alicia",
    apellidos: "Valiente",
    ci: "920151569",
    telefono: "5814566",
    puesto: "Fotografo",
    direccion: "Calle 78 #11 Reparto La Cuevita",
    salario: 75000,
    foto_perfil: "alicia.jpg",
    id_usuario: 2,
  },
  {
    id_trabajador: 3,
    nombre: "Berta",
    apellidos: "Fonseca",
    ci: "920151569",
    telefono: "5814566",
    puesto: "Editora",
    direccion: "Calle 20 #112 Reparto La Quinta",
    salario: 75000,
    foto_perfil: "alicia.jpg",
    id_usuario: 5,
  },
  {
    id_trabajador: 4,
    nombre: "Keila",
    apellidos: "Gonzales",
    ci: "920151569",
    telefono: "5814566",
    puesto: "Estilista",
    direccion: "Km 8 #11 San Rafael",
    salario: 75000,
    foto_perfil: "keila.jpg",
    id_usuario: 20,
  },
];
